export const Colors = {
  primary: "#6849a7",
  warning: "#cc475a",
  light: {
    background: '#F8F9FA',
    text: '#212529',
    primary: '#4CAF50',
    secondary: '#8BC34A',
    buttonText: '#FFFFFF',
    inputBackground: '#FFFFFF',
    placeholderTextColor: "#666",
    tabBarBackground: '#fff', 
    tabBarBorderTopColor: '#ccc',
    activeTintColor: 'green',
    inactiveTintColor: '#666',
  },
  dark: {
    background: '#121212',
    text: '#FFFFFF',
    primary: '#66BB6A',
    secondary: '#A5D6A7',
    buttonText: '#000000',
    inputBackground: '#1E1E1E',
    placeholderTextColor: "#AAA",
    tabBarBackground: '#000',
    tabBarBorderTopColor: '#222',
    activeTintColor: '#90ee90',
    inactiveTintColor: '#aaa',
  },
};